### ISSUE TITLE
Decide whether to enhance the dashboard or switch to an off-the-shelf system

### ISSUE THREAD

**Issue by anjackson** [ukwa/ukwa-monitor#3]
Currently the system runs it's own simple (if rather dense) dashboard, as a basic Python Flask app and a simple template that formats the result of the monitoring tasks (stored on disk).

Originally, we were planning to stick with this approach, but move towards a schematic representation of our service using CSS to indicate status (see [overview.svg](https://github.com/ukwa/ukwa-monitor/blob/master/webapp/templates/overview.svg)). Perhaps enhanced with a few trend plots (e.g. using [plot.ly](https://plot.ly/python/dashboard/)) as required.

An alternative is to just use some off-the-shelf dashboard that's fancier and configurable:

- [Kibana](https://www.elastic.co/products/kibana)
- [Grafana](https://grafana.com/)
- [Prometheus](https://prometheus.io/)
- ...and many more...
- Or just to integrate with the existing Nagios installation.

There's various things we'd ideally like to add to our monitoring dashboard, like screenshots of crawled pages, which would lean towards having our own simple dashboard. However, perhaps this an unrealistic amount of effort? It's difficult to see the pay-off unless these are systems we can use to debug problems, not just be alerted to them.

**Comment by GilHoggarth** [comment]
I'd vote for the current simple approach. Simplistic, very low installation on servers, but I think we should prioritise the alerts we need to see like crawlers paused, Hadoop state, public website state - at least for the moment.

**Comment by anjackson** [comment]
The problem with the current 'simplistic' solution is that it is more custom code to maintain, and thus it is harder to modify/update. So, we'll stick with the current while we don't need to change much, but move to Grafana later on (Grafana because that's also used by HDP, so there's not much point running both Kibana and Grafana).
