### ISSUE TITLE
Move Gluster-filling-up metric to something more reliable

### ISSUE THREAD

**Issue by anjackson** [ukwa/ukwa-monitor#33]
The current gluster-filling-up alert uses `delta()` and I'm not sure what it's doing because it's not very easy to interpret.  See e.g.  [this comparison with `delta()` and `deriv()`](http://monitor-prometheus.api.wa.bl.uk/graph?g0.expr=-delta(node_filesystem_free_bytes%7Binstance%3D%22gluster-fuse%3A9100%22%2Cmountpoint%3D%22%2Fmnt%2Fgluster%2Ffc%22%7D%5B12h%5D)%20%3E%200&g0.tab=0&g0.stacked=0&g0.show_exemplars=0&g0.range_input=26w&g1.expr=deriv(node_filesystem_free_bytes%7Binstance%3D%22gluster-fuse%3A9100%22%2Cmountpoint%3D%22%2Fmnt%2Fgluster%2Ffc%22%7D%5B24h%5D)%20%3E%201e6&g1.tab=0&g1.stacked=0&g1.show_exemplars=0&g1.range_input=26w)

That link includes this alternative implementation:

```
deriv(node_filesystem_free_bytes{instance="gluster-fuse:9100",mountpoint="/mnt/gluster/fc"}[24h]) > 1e6
```

This seems a but more stable, so I suggest we switch to that instead of 

https://github.com/ukwa/ukwa-monitor/blob/5c6f589d02b834562c790b3bc9ad0b40e1b67232/monitor/prometheus/alert.rules.yml#L141

**Comment by anjackson** [comment]
Not urgent, but could you bundle this change in next time you update monitoring.  Maybe we should start using Milestones to bunch a few updates together (e.g. including Hadoop3 ones).

**Comment by GilHoggarth** [comment]
Updated in latest commit.
